library(ggmsa)
library(here)

msa1 <- here('./data/prem_cl/gl_dup.fa')
pdf(here('./figs/gl_dup_s3g_raw.pdf'))
ggmsa(msa1, none_bg = TRUE, font = "helvetical", char_width = .8, seq_name = TRUE) 
dev.off()
msa2 <- here('./data/prem_cl/gs_dup.fa')
pdf(here('./figs/gs_dup_s3h_raw.pdf'))
ggmsa(msa2, none_bg = TRUE, font = "helvetical", char_width = .8, seq_name = TRUE) 
dev.off()
